language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
        - dev
before_script:
    - chmod -R a+x scripts
script:
    - "./scripts/travis-build.sh"
after_success:
    - "./scripts/travis-docker-publish.sh"
notifications:
    email: false
    slack:
        secure: kXlAUGrhqlJEe6IkeGig7Fmdpktka7n+3OSXgFBkn24o/T6Jsxs4gwd/FBm756K6B1cAos3N5j66IpGj6LZ4rgLBKXkASRayLkjGwKQ2aIhhg2CtJChxPkxlrpbCB8ghzzpFS6rsk9GsNBcuqfsTChSrG6cD2UQiE/5Ygzma/GuMDpZAq8E4UO9tOXXRvBzfEfUCLK/A4EKa1A8lPyHuzPAZfqG11OMpjvhPOz3N/LuhB8CUZb7UzZcc6oJBOmD2ODEg8NkK8xjC8nn1HMy84tfXJlpBVyEjJVdxso12NT/iRN9Apgl9Xk3kgXPPKtEgm7jjqd2Y1NxEeCsWg4HiV/PyC0IjX1ihtqIl/jmGvXg7Nox1BSPNujXxdhUTevmP59s5CCZ8Xkmwk1MByP8wVZGVH+ytMikuLr3sU/YbGIrOFAh4JJ5El8mqcPlrX9UU9XiUfRixXZId3+FlE2cvWiFlLI2pY1/YtQImLQ1z3g/j69SaKxKQoE83iNbIq+2UTv0xm/sm+V9pMQEXgnIoMEaUv0o9aSk3hVJdrk2z2EEoA/btrJklnZNP0RYIX/bBlSyrefRpUg8U9F3c2smEH6aif5iv1HzWkMDNUMNh/NAgoI/WOv3naWAUV2/ouLJPnFgOKP15xdTGHGKeIM9sz+hwT73vX3D9O1fH8PJvY+U=
