version: "3.5"
services:
    postgres:
        image: postgres:9.5
        container_name: notifications_postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        networks:
            - notifications
        volumes:
            - postgres:/data/db
    redis:
        image: redis
        container_name: notifications_redis
        ports:
            - "6379:6379"
        networks:
            - notifications
        volumes:
            - redis:/data

networks:
    notifications:
        name: notifications-network
        internal: true

volumes:
    postgres:
        driver: local
    redis:
        driver: local
