version: '3.5'
services:
    api:
        image: ranger.services.notifications:dev
        container_name: notifications
        ports:
            - '8084:8084'
        networks:
            - ranger

networks:
    ranger:
        name: ranger-network
        external: true
